import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
const prisma = new PrismaClient();

const productImageIds = [
  "1542838132-92c53300491e",
  "1566385101042-1a0aa68c5e47",
  "1619566626922-71c5935a3e8c",
  "1628088062854-b1870b1f6b9f",
  "1509440159596-0249088772ff",
  "1596040033229-a9821ebd058d",
];

function getProductImage(index: number): string {
  return `https://images.unsplash.com/photo-${productImageIds[index % productImageIds.length]}?w=400&h=400&fit=crop`;
}

async function main() {
  console.log("Seeding database...");

  const categories = [
    {
      name: "Vegetables",
      slug: "vegetables",
      image: "https://images.unsplash.com/photo-1566385101042-1a0aa68c5e47?w=400&h=400&fit=crop",
      products: [
        { name: "Fresh Tomatoes", price: 30, compareAt: 40, unit: "1 KG", stock: 100, description: "Juicy, ripe tomatoes perfect for salads and cooking." },
        { name: "Potatoes", price: 25, compareAt: 35, unit: "1 KG", stock: 150, description: "High-quality potatoes ideal for curries and fries." },
        { name: "Onions", price: 28, compareAt: 38, unit: "1 KG", stock: 150, description: "Fresh red onions with strong flavor for everyday cooking." },
        { name: "Spinach", price: 15, compareAt: 20, unit: "1 Bunch", stock: 80, description: "Fresh green spinach leaves rich in iron and nutrients." },
        { name: "Cauliflower", price: 35, compareAt: 45, unit: "1 Piece", stock: 60, description: "Fresh, firm cauliflower heads for sabzi and parathas." },
        { name: "Cabbage", price: 20, compareAt: 28, unit: "1 Piece", stock: 70, description: "Crisp green cabbage for salads and stir-fries." },
        { name: "Cucumber", price: 25, compareAt: 32, unit: "1 KG", stock: 90, description: "Cool and crunchy cucumbers fresh from the farm." },
        { name: "Carrots", price: 30, compareAt: 38, unit: "1 KG", stock: 100, description: "Sweet, tender carrots packed with vitamin A." },
        { name: "Beetroot", price: 35, compareAt: 45, unit: "1 KG", stock: 60, description: "Deep red beetroots rich in antioxidants and minerals." },
        { name: "Green Beans", price: 40, compareAt: 50, unit: "1 KG", stock: 70, description: "Crunchy French beans freshly harvested from local farms." },
        { name: "Peas", price: 45, compareAt: 55, unit: "1 KG", stock: 65, description: "Sweet and tender green peas perfect for pulao." },
        { name: "Bell Pepper Red", price: 60, compareAt: 78, unit: "1 KG", stock: 50, description: "Vibrant red bell peppers rich in vitamin C." },
        { name: "Bell Pepper Green", price: 40, compareAt: 55, unit: "1 KG", stock: 55, description: "Fresh green capsicum with a mild, crisp flavor." },
        { name: "Brinjal / Eggplant", price: 25, compareAt: 35, unit: "1 KG", stock: 75, description: "Glossy purple brinjals great for baingan bharta." },
        { name: "Ladyfinger / Okra", price: 30, compareAt: 40, unit: "1 KG", stock: 80, description: "Tender okra pods, perfect for bhindi masala." },
        { name: "Pumpkin", price: 20, compareAt: 28, unit: "1 KG", stock: 40, description: "Sweet orange pumpkin for sabzi and soups." },
        { name: "Mushrooms", price: 80, compareAt: 100, unit: "250 GM", stock: 40, description: "Fresh button mushrooms, cleaned and ready to cook." },
        { name: "Corn on Cob", price: 25, compareAt: 35, unit: "1 Piece", stock: 80, description: "Sweet yellow corn cobs for roasting and boiling." },
        { name: "Spring Onions", price: 18, compareAt: 25, unit: "1 Bunch", stock: 70, description: "Fresh spring onions with green tops for garnish." },
        { name: "Green Chili", price: 12, compareAt: 18, unit: "250 GM", stock: 100, description: "Spicy green chillies to add heat to your dishes." },
        { name: "Ginger", price: 40, compareAt: 55, unit: "250 GM", stock: 80, description: "Fresh ginger rhizomes with strong aromatic flavor." },
        { name: "Garlic", price: 35, compareAt: 48, unit: "250 GM", stock: 90, description: "Premium garlic cloves, essential for Indian cooking." },
        { name: "Sweet Potato", price: 40, compareAt: 50, unit: "1 KG", stock: 60, description: "Nutritious sweet potatoes rich in fiber and vitamins." },
        { name: "Coriander Leaves", price: 10, compareAt: 15, unit: "1 Bunch", stock: 100, description: "Fresh coriander leaves for garnishing and chutneys." },
        { name: "Curry Leaves", price: 8, compareAt: 12, unit: "1 Bunch", stock: 90, description: "Aromatic curry leaves essential for South Indian tadka." },
      ],
    },
    {
      name: "Fruits",
      slug: "fruits",
      image: "https://images.unsplash.com/photo-1619566626922-71c5935a3e8c?w=400&h=400&fit=crop",
      products: [
        { name: "Red Apples", price: 150, compareAt: 180, unit: "1 KG", stock: 80, description: "Crisp and juicy red apples from Kashmir." },
        { name: "Bananas", price: 30, compareAt: 40, unit: "1 Dozen", stock: 150, description: "Ripe yellow bananas, naturally sweet and filling." },
        { name: "Oranges", price: 80, compareAt: 100, unit: "1 KG", stock: 90, description: "Juicy Nagpur oranges bursting with citrus flavor." },
        { name: "Grapes Green", price: 70, compareAt: 90, unit: "1 KG", stock: 65, description: "Seedless green grapes, sweet and refreshing." },
        { name: "Pomegranate", price: 120, compareAt: 148, unit: "1 KG", stock: 60, description: "Ruby red pomegranate arils rich in antioxidants." },
        { name: "Mango Alphonso", price: 250, compareAt: 300, unit: "1 Dozen", stock: 40, description: "Premium Alphonso mangoes, the king of fruits." },
        { name: "Watermelon", price: 30, compareAt: 40, unit: "1 KG", stock: 35, description: "Sweet and juicy watermelon perfect for summer." },
        { name: "Muskmelon", price: 50, compareAt: 65, unit: "1 Piece", stock: 30, description: "Aromatic muskmelon with sweet orange flesh." },
        { name: "Papaya", price: 45, compareAt: 58, unit: "1 Piece", stock: 45, description: "Ripe papaya rich in papain enzymes and vitamin C." },
        { name: "Pineapple", price: 80, compareAt: 100, unit: "1 Piece", stock: 35, description: "Sweet golden pineapple, freshly sourced." },
        { name: "Strawberries", price: 200, compareAt: 250, unit: "1 Box", stock: 30, description: "Fresh and juicy strawberries from Mahabaleshwar." },
        { name: "Kiwi", price: 180, compareAt: 220, unit: "1 KG", stock: 40, description: "Green kiwi fruit packed with vitamin C and fiber." },
        { name: "Guava", price: 50, compareAt: 65, unit: "1 KG", stock: 55, description: "Aromatic guavas sweet and rich in vitamin C." },
        { name: "Sapota / Chikoo", price: 60, compareAt: 78, unit: "1 KG", stock: 40, description: "Sweet and grainy sapota with caramel-like flavor." },
        { name: "Dragon Fruit", price: 160, compareAt: 200, unit: "1 KG", stock: 25, description: "Exotic dragon fruit with mildly sweet white flesh." },
        { name: "Plums", price: 120, compareAt: 150, unit: "1 KG", stock: 35, description: "Dark purple plums with sweet-tart flavor." },
        { name: "Pears", price: 140, compareAt: 175, unit: "1 KG", stock: 40, description: "Sweet and juicy pears perfect for snacking." },
        { name: "Coconut Tender", price: 35, compareAt: 50, unit: "1 Piece", stock: 60, description: "Fresh tender coconut with sweet refreshing water." },
        { name: "Lychee", price: 180, compareAt: 220, unit: "1 KG", stock: 25, description: "Sweet and fragrant lychees from Bihar." },
        { name: "Custard Apple", price: 100, compareAt: 130, unit: "1 KG", stock: 30, description: "Creamy custard apple with naturally sweet pulp." },
      ],
    },
    {
      name: "Dairy, Eggs & Cheese",
      slug: "dairy-eggs-cheese",
      image: "https://images.unsplash.com/photo-1628088062854-b1870b1f6b9f?w=400&h=400&fit=crop",
      products: [
        { name: "Fresh Cow Milk", price: 60, compareAt: 75, unit: "1 Ltr", stock: 100, description: "Pure fresh cow milk from local dairy farms." },
        { name: "Toned Milk", price: 50, compareAt: 62, unit: "1 Ltr", stock: 120, description: "Low-fat toned milk with balanced nutrition." },
        { name: "Full Cream Milk", price: 68, compareAt: 84, unit: "1 Ltr", stock: 90, description: "Rich full-cream milk with high butterfat content." },
        { name: "Curd / Yogurt", price: 40, compareAt: 50, unit: "500 GM", stock: 80, description: "Thick and creamy fresh curd made from cow milk." },
        { name: "Greek Yogurt", price: 85, compareAt: 105, unit: "500 GM", stock: 40, description: "Strained Greek yogurt with high protein content." },
        { name: "Buttermilk", price: 25, compareAt: 35, unit: "1 Ltr", stock: 70, description: "Spiced buttermilk refreshing and good for digestion." },
        { name: "Fresh Paneer", price: 120, compareAt: 150, unit: "250 GM", stock: 50, description: "Soft and fresh cottage cheese made from pure milk." },
        { name: "Mozzarella Cheese", price: 180, compareAt: 220, unit: "200 GM", stock: 40, description: "Stretchy mozzarella cheese perfect for pizzas." },
        { name: "Cheddar Cheese", price: 200, compareAt: 250, unit: "200 GM", stock: 35, description: "Sharp aged cheddar cheese block for grating." },
        { name: "Processed Cheese", price: 95, compareAt: 120, unit: "200 GM", stock: 60, description: "Creamy processed cheese slices great for sandwiches." },
        { name: "Butter Unsalted", price: 55, compareAt: 70, unit: "100 GM", stock: 70, description: "Creamy unsalted butter made from fresh cream." },
        { name: "Ghee Clarified", price: 280, compareAt: 350, unit: "500 ML", stock: 45, description: "Pure desi ghee with rich aroma and taste." },
        { name: "Fresh Cream", price: 65, compareAt: 82, unit: "200 ML", stock: 55, description: "Thick fresh cream for desserts and curries." },
        { name: "Farm Eggs", price: 72, compareAt: 90, unit: "6 Pieces", stock: 120, description: "Fresh farm eggs from free-range hens." },
        { name: "Free Range Eggs", price: 96, compareAt: 120, unit: "6 Pieces", stock: 80, description: "Organic free-range eggs with deep orange yolks." },
        { name: "Organic Eggs", price: 120, compareAt: 150, unit: "6 Pieces", stock: 50, description: "Certified organic eggs from antibiotic-free hens." },
        { name: "Condensed Milk", price: 80, compareAt: 100, unit: "400 GM", stock: 45, description: "Sweetened condensed milk for desserts and baking." },
        { name: "Milk Powder", price: 220, compareAt: 275, unit: "1 KG", stock: 35, description: "Full cream milk powder with long shelf life." },
        { name: "Flavored Yogurt Mango", price: 50, compareAt: 65, unit: "150 ML", stock: 50, description: "Creamy mango flavored yogurt in convenient cup." },
        { name: "Shrikhand", price: 90, compareAt: 115, unit: "200 GM", stock: 35, description: "Traditional Gujarati sweet yogurt dessert." },
        { name: "Lassi Sweet", price: 35, compareAt: 48, unit: "200 ML", stock: 60, description: "Refreshing sweet yogurt drink, perfectly blended." },
      ],
    },
    {
      name: "Bread & Bakery",
      slug: "bread-bakery",
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop",
      products: [
        { name: "White Sandwich Bread", price: 35, compareAt: 45, unit: "400 GM", stock: 80, description: "Soft white bread perfect for daily sandwiches." },
        { name: "Brown Bread", price: 45, compareAt: 58, unit: "400 GM", stock: 70, description: "Healthy brown bread with whole wheat goodness." },
        { name: "Multigrain Bread", price: 55, compareAt: 70, unit: "400 GM", stock: 55, description: "Nutritious multigrain bread with seeds and grains." },
        { name: "Whole Wheat Bread", price: 50, compareAt: 65, unit: "400 GM", stock: 65, description: "100% whole wheat bread rich in fiber." },
        { name: "Garlic Bread", price: 75, compareAt: 95, unit: "1 Pack", stock: 40, description: "Crusty garlic bread with butter and herbs." },
        { name: "Croissants", price: 90, compareAt: 115, unit: "2 Pieces", stock: 35, description: "Flaky butter croissants baked fresh daily." },
        { name: "Baguette", price: 55, compareAt: 70, unit: "1 Piece", stock: 35, description: "French baguette with crispy crust and soft crumb." },
        { name: "Pita Bread", price: 40, compareAt: 52, unit: "6 Pieces", stock: 50, description: "Soft pita bread pockets perfect for wraps." },
        { name: "Naan Plain", price: 30, compareAt: 40, unit: "4 Pieces", stock: 60, description: "Soft restaurant-style naan bread ready to heat." },
        { name: "Roti / Chapati", price: 25, compareAt: 35, unit: "10 Pieces", stock: 80, description: "Fresh whole wheat rotis made the traditional way." },
        { name: "Paratha Plain", price: 35, compareAt: 48, unit: "5 Pieces", stock: 65, description: "Flaky layered parathas ready to pan-fry." },
        { name: "Pav / Dinner Rolls", price: 20, compareAt: 28, unit: "6 Pieces", stock: 90, description: "Soft and fluffy pav buns for your meals." },
        { name: "Burger Buns", price: 35, compareAt: 45, unit: "4 Pieces", stock: 60, description: "Sesame topped burger buns soft and fresh." },
        { name: "Muffins Blueberry", price: 80, compareAt: 100, unit: "2 Pieces", stock: 35, description: "Moist blueberry muffins bursting with berries." },
        { name: "Cookies Chocolate Chip", price: 65, compareAt: 82, unit: "6 Pieces", stock: 50, description: "Crunchy chocolate chip cookies baked to perfection." },
        { name: "Brownies", price: 90, compareAt: 115, unit: "3 Pieces", stock: 35, description: "Rich fudgy chocolate brownies with walnuts." },
        { name: "Banana Bread", price: 75, compareAt: 95, unit: "1 Loaf", stock: 30, description: "Moist banana bread made with ripe bananas." },
        { name: "Sourdough Bread", price: 80, compareAt: 100, unit: "1 Loaf", stock: 30, description: "Artisan sourdough with tangy flavor and crusty finish." },
        { name: "Cupcakes Vanilla", price: 100, compareAt: 128, unit: "4 Pieces", stock: 25, description: "Light vanilla cupcakes with buttercream frosting." },
        { name: "Donuts Glazed", price: 60, compareAt: 78, unit: "4 Pieces", stock: 40, description: "Soft glazed donuts with sugary sweet topping." },
      ],
    },
    {
      name: "Beverages",
      slug: "beverages",
      image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=400&fit=crop",
      products: [
        { name: "Bisleri Water 1L", price: 20, compareAt: 25, unit: "1 Ltr", stock: 200, description: "Pure mineral water from Bisleri, safe and clean." },
        { name: "Kinley Water 500ml", price: 12, compareAt: 18, unit: "500 ML", stock: 200, description: "Packaged drinking water from Coca-Cola." },
        { name: "Coca-Cola 750ml", price: 40, compareAt: 50, unit: "750 ML", stock: 150, description: "Classic Coca-Cola refreshing carbonated beverage." },
        { name: "Pepsi 750ml", price: 40, compareAt: 50, unit: "750 ML", stock: 150, description: "Pepsi cola with its signature bold taste." },
        { name: "Sprite 750ml", price: 40, compareAt: 50, unit: "750 ML", stock: 150, description: "Crisp lemon-lime soda, caffeine free." },
        { name: "Fanta 750ml", price: 40, compareAt: 50, unit: "750 ML", stock: 130, description: "Fruity orange soda with bubbly refreshment." },
        { name: "Thums Up 750ml", price: 42, compareAt: 52, unit: "750 ML", stock: 140, description: "India's favorite strong cola drink." },
        { name: "Maaza Mango Drink", price: 50, compareAt: 65, unit: "1 Ltr", stock: 100, description: "Thick mango juice made from Alphonso mangoes." },
        { name: "Real Juice Orange", price: 90, compareAt: 115, unit: "1 Ltr", stock: 80, description: "Pure orange juice with no added preservatives." },
        { name: "Tropicana Apple", price: 85, compareAt: 108, unit: "1 Ltr", stock: 75, description: "Refreshing apple juice from Tropicana." },
        { name: "B Natural Mixed Fruit", price: 80, compareAt: 100, unit: "1 Ltr", stock: 70, description: "Mixed fruit juice with real pulp." },
        { name: "Paper Boat Aamras", price: 45, compareAt: 58, unit: "200 ML", stock: 90, description: "Traditional mango pulp drink in tetra pack." },
        { name: "Gatorade Lemon", price: 60, compareAt: 78, unit: "500 ML", stock: 60, description: "Isotonic sports drink for quick energy." },
        { name: "Red Bull 250ml", price: 115, compareAt: 140, unit: "250 ML", stock: 50, description: "Energy drink that gives you wings." },
        { name: "Limca 750ml", price: 40, compareAt: 50, unit: "750 ML", stock: 130, description: "Lime and lemon flavored carbonated drink." },
        { name: "7UP 750ml", price: 40, compareAt: 50, unit: "750 ML", stock: 120, description: "Clear lemon drink with crisp taste." },
        { name: "Appy Fizz", price: 35, compareAt: 45, unit: "250 ML", stock: 100, description: "Sparkling apple juice with a fizzy twist." },
        { name: "Nimbooz Masala", price: 25, compareAt: 35, unit: "200 ML", stock: 110, description: "Ready-to-drink lemon soda with masala twist." },
        { name: "Coca-Cola Zero", price: 40, compareAt: 50, unit: "750 ML", stock: 100, description: "Zero calorie Coca-Cola, same great taste." },
        { name: "Pepsi Black", price: 40, compareAt: 50, unit: "750 ML", stock: 90, description: "No sugar Pepsi with bold cola flavor." },
      ],
    },
    {
      name: "Snacks & Munchies",
      slug: "snacks-munchies",
      image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=400&fit=crop",
      products: [
        { name: "Lays Classic Salted", price: 20, compareAt: 25, unit: "1 Pack", stock: 200, description: "Classic salted potato chips crispy and delicious." },
        { name: "Lays Magic Masala", price: 20, compareAt: 25, unit: "1 Pack", stock: 200, description: "Indian masala flavored chips with a spicy kick." },
        { name: "Lays Sour Cream", price: 20, compareAt: 25, unit: "1 Pack", stock: 180, description: "Creamy sour cream and onion flavored chips." },
        { name: "Kurkure Masala Munch", price: 10, compareAt: 15, unit: "1 Pack", stock: 250, description: "Crunchy masala corn snacks loved by all." },
        { name: "Pringles Original", price: 95, compareAt: 120, unit: "1 Can", stock: 60, description: "Stackable potato crisps in a signature can." },
        { name: "Doritos Nacho Cheese", price: 30, compareAt: 40, unit: "1 Pack", stock: 100, description: "Tangy nacho cheese flavored tortilla chips." },
        { name: "Cheetos Puffs", price: 20, compareAt: 28, unit: "1 Pack", stock: 150, description: "Cheesy puff snacks that melt in your mouth." },
        { name: "Haldiram Aloo Bhujia", price: 35, compareAt: 45, unit: "200 GM", stock: 120, description: "Crispy aloo bhujia namkeen from Haldiram." },
        { name: "Haldiram Bhel Puri", price: 40, compareAt: 50, unit: "200 GM", stock: 80, description: "Ready-to-eat bhel puri mix with chutney." },
        { name: "Balaji Wafers Classic", price: 20, compareAt: 28, unit: "1 Pack", stock: 160, description: "Popular Gujarat-style salted potato wafers." },
        { name: "Bingo Mad Angles", price: 20, compareAt: 25, unit: "1 Pack", stock: 150, description: "Triangular tortilla chips with tangy flavor." },
        { name: "Bingo Teddy", price: 10, compareAt: 15, unit: "1 Pack", stock: 200, description: "Teddy-shaped rice snacks fun for kids." },
        { name: "Uncle Chipps Classic", price: 20, compareAt: 28, unit: "1 Pack", stock: 170, description: "Classic salted chips made from real potatoes." },
        { name: "Too Yumm Multigrain", price: 20, compareAt: 28, unit: "1 Pack", stock: 130, description: "Healthy multigrain chips in spicy tomato flavor." },
        { name: "Snickers Bar", price: 40, compareAt: 50, unit: "1 Bar", stock: 100, description: "Chocolate bar with nougat, caramel and peanuts." },
        { name: "KitKat", price: 30, compareAt: 40, unit: "1 Bar", stock: 120, description: "Crisp wafers covered in smooth milk chocolate." },
        { name: "M&M's Peanut", price: 45, compareAt: 58, unit: "1 Pack", stock: 90, description: "Colorful candy-coated peanuts in milk chocolate." },
        { name: "Dairy Milk Silk", price: 50, compareAt: 65, unit: "1 Bar", stock: 110, description: "Silky smooth Cadbury milk chocolate bar." },
        { name: "Cadbury 5 Star", price: 25, compareAt: 35, unit: "1 Bar", stock: 130, description: "Chewy chocolate caramel bar, deliciously crunchy." },
        { name: "Parle G", price: 10, compareAt: 15, unit: "1 Pack", stock: 300, description: "India's favorite glucose biscuit since 1929." },
        { name: "Hide & Seek Biscuits", price: 30, compareAt: 40, unit: "1 Pack", stock: 100, description: "Chocolate chip cookies with hidden treat." },
        { name: "Good Day Biscuits", price: 25, compareAt: 35, unit: "1 Pack", stock: 120, description: "Cashew and butter cookies from Britannia." },
      ],
    },
    {
      name: "Breakfast & Cereals",
      slug: "breakfast-cereals",
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop",
      products: [
        { name: "Kellogg's Corn Flakes", price: 150, compareAt: 185, unit: "500 GM", stock: 60, description: "Classic toasted corn flakes breakfast cereal." },
        { name: "Kellogg's Muesli Fruit", price: 250, compareAt: 310, unit: "500 GM", stock: 40, description: "Swiss style muesli with dried fruits and nuts." },
        { name: "Quaker Oats", price: 120, compareAt: 150, unit: "500 GM", stock: 70, description: "Rolled oats rich in fiber and heart healthy." },
        { name: "Saffola Oats", price: 135, compareAt: 170, unit: "500 GM", stock: 55, description: "Masala oats with vegetables, ready in minutes." },
        { name: "Bagrry's Muesli", price: 220, compareAt: 275, unit: "500 GM", stock: 35, description: "Crunchy muesli with nuts, seeds and dried fruits." },
        { name: "Kellogg's Special K", price: 180, compareAt: 225, unit: "500 GM", stock: 40, description: "Crispy rice and wheat cereal for weight management." },
        { name: "Kellogg's Chocos", price: 160, compareAt: 200, unit: "500 GM", stock: 50, description: "Chocolate flavored breakfast cereal loved by kids." },
        { name: "Kellogg's Froot Loops", price: 170, compareAt: 210, unit: "500 GM", stock: 35, description: "Colorful fruit-flavored breakfast rings." },
        { name: "Oatmeal Instant Pack", price: 80, compareAt: 100, unit: "1 Pack", stock: 60, description: "Instant oatmeal packets with assorted flavors." },
        { name: "Wheat Flakes", price: 110, compareAt: 140, unit: "500 GM", stock: 45, description: "Toasted wheat flakes with honey, light and crispy." },
        { name: "Kellogg's All Bran", price: 200, compareAt: 250, unit: "500 GM", stock: 30, description: "High fiber wheat bran cereal for digestive health." },
        { name: "Granola Bar Honey", price: 60, compareAt: 78, unit: "1 Bar", stock: 100, description: "Honey almond granola bar for on-the-go energy." },
        { name: "Protein Granola", price: 280, compareAt: 350, unit: "500 GM", stock: 25, description: "High protein granola with seeds and nuts." },
        { name: "Millets Flakes", price: 95, compareAt: 120, unit: "500 GM", stock: 40, description: "Organic millet flakes gluten-free breakfast." },
        { name: "Choco Granola", price: 260, compareAt: 320, unit: "500 GM", stock: 30, description: "Chocolate granola clusters with crunchy texture." },
        { name: "Poha Flakes", price: 40, compareAt: 52, unit: "500 GM", stock: 90, description: "Traditional beaten rice flakes for quick breakfast." },
        { name: "Rava / Semolina", price: 35, compareAt: 48, unit: "500 GM", stock: 100, description: "Fine semolina for upma and rava dosa." },
      ],
    },
    {
      name: "Rice, Pasta & Noodles",
      slug: "rice-pasta-noodles",
      image: "https://images.unsplash.com/photo-1628088062854-b1870b1f6b9f?w=400&h=400&fit=crop",
      products: [
        { name: "Basmati Rice Premium", price: 180, compareAt: 225, unit: "1 KG", stock: 80, description: "Premium long grain basmati rice for biryani." },
        { name: "Sona Masoori Rice", price: 75, compareAt: 95, unit: "1 KG", stock: 100, description: "Light and aromatic everyday rice from South India." },
        { name: "Ponni Rice", price: 65, compareAt: 82, unit: "1 KG", stock: 90, description: "Popular Tamil Nadu rice variety for daily use." },
        { name: "Brown Rice", price: 95, compareAt: 120, unit: "1 KG", stock: 60, description: "Unpolished brown rice rich in fiber and nutrients." },
        { name: "Idli Rice", price: 55, compareAt: 70, unit: "1 KG", stock: 75, description: "Parboiled rice specially milled for idli and dosa." },
        { name: "Pasta Penne", price: 70, compareAt: 88, unit: "500 GM", stock: 50, description: "Italian penne pasta great with tomato sauce." },
        { name: "Pasta Fusilli", price: 70, compareAt: 88, unit: "500 GM", stock: 45, description: "Spiral fusilli pasta ideal for pasta salads." },
        { name: "Pasta Macaroni", price: 60, compareAt: 78, unit: "500 GM", stock: 55, description: "Elbow macaroni perfect for cheesy pasta bakes." },
        { name: "Maggi Noodles Classic", price: 14, compareAt: 20, unit: "1 Pack", stock: 300, description: "Classic 2-minute Maggi noodles, India's favorite." },
        { name: "Top Ramen Noodles", price: 12, compareAt: 18, unit: "1 Pack", stock: 250, description: "Quick-cooking noodles from Indo Nissin." },
        { name: "Yippee Noodles", price: 14, compareAt: 20, unit: "1 Pack", stock: 200, description: "Fun-filled noodles with tasty masala seasoning." },
        { name: "Spaghetti", price: 65, compareAt: 82, unit: "500 GM", stock: 50, description: "Authentic Italian spaghetti for pasta dishes." },
        { name: "Lasagne Sheets", price: 120, compareAt: 150, unit: "500 GM", stock: 30, description: "Flat lasagne pasta sheets for baked dishes." },
        { name: "Vermicelli / Semiya", price: 45, compareAt: 58, unit: "500 GM", stock: 70, description: "Fine vermicelli for kheer and upma." },
        { name: "Rice Flour", price: 50, compareAt: 65, unit: "1 KG", stock: 65, description: "Finely milled rice flour for dosa and snacks." },
        { name: "Semolina / Rava", price: 35, compareAt: 48, unit: "500 GM", stock: 80, description: "Coarse semolina perfect for upma and halwa." },
        { name: "Instant Noodles Cup", price: 30, compareAt: 40, unit: "1 Cup", stock: 150, description: "Ready-to-eat noodle cup just add hot water." },
        { name: "Hakka Noodles", price: 80, compareAt: 100, unit: "500 GM", stock: 40, description: "Pre-cooked hakka noodles for stir-fry dishes." },
      ],
    },
    {
      name: "Cooking Oils & Ghee",
      slug: "cooking-oils-ghee",
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop",
      products: [
        { name: "Mustard Oil", price: 180, compareAt: 225, unit: "1 Ltr", stock: 70, description: "Pure mustard oil with pungent aroma and flavor." },
        { name: "Sunflower Oil", price: 160, compareAt: 200, unit: "1 Ltr", stock: 80, description: "Light sunflower oil for everyday cooking needs." },
        { name: "Olive Oil Extra Virgin", price: 450, compareAt: 550, unit: "500 ML", stock: 40, description: "Cold-pressed extra virgin olive oil for salads." },
        { name: "Rice Bran Oil", price: 140, compareAt: 175, unit: "1 Ltr", stock: 65, description: "Heart-healthy rice bran oil with light taste." },
        { name: "Groundnut Oil", price: 200, compareAt: 250, unit: "1 Ltr", stock: 50, description: "Traditional cold-pressed groundnut oil." },
        { name: "Coconut Oil", price: 170, compareAt: 210, unit: "500 ML", stock: 60, description: "Pure virgin coconut oil for cooking and hair." },
        { name: "Soybean Oil", price: 130, compareAt: 165, unit: "1 Ltr", stock: 90, description: "Economical soybean oil for daily cooking." },
        { name: "Ghee Cow", price: 350, compareAt: 430, unit: "500 ML", stock: 45, description: "Pure cow ghee with rich nutty flavor." },
        { name: "Ghee Buffalo", price: 280, compareAt: 350, unit: "500 ML", stock: 40, description: "Traditional buffalo ghee for authentic taste." },
        { name: "Avocado Oil", price: 550, compareAt: 680, unit: "500 ML", stock: 20, description: "Premium cold-pressed avocado oil high in good fats." },
        { name: "Sesame Oil", price: 220, compareAt: 275, unit: "500 ML", stock: 35, description: "Toasted sesame oil for Asian cooking and stir-fry." },
        { name: "Canola Oil", price: 145, compareAt: 180, unit: "1 Ltr", stock: 55, description: "Light canola oil low in saturated fats." },
        { name: "Palm Oil", price: 110, compareAt: 140, unit: "1 Ltr", stock: 60, description: "Refined palm oil for deep frying and cooking." },
        { name: "Almond Oil", price: 300, compareAt: 380, unit: "100 ML", stock: 25, description: "Cold-pressed almond oil for skin and hair." },
        { name: "Coconut Oil Cooking", price: 190, compareAt: 240, unit: "1 Ltr", stock: 50, description: "Refined coconut oil with neutral taste for cooking." },
      ],
    },
    {
      name: "Spices & Seasonings",
      slug: "spices-seasonings",
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop",
      products: [
        { name: "Turmeric Powder", price: 80, compareAt: 100, unit: "200 GM", stock: 70, description: "Pure turmeric powder with high curcumin content." },
        { name: "Red Chili Powder", price: 65, compareAt: 82, unit: "200 GM", stock: 80, description: "Spicy red chili powder for authentic Indian heat." },
        { name: "Coriander Powder", price: 55, compareAt: 70, unit: "200 GM", stock: 75, description: "Aromatic ground coriander for curries and masala." },
        { name: "Cumin Seeds / Jeera", price: 70, compareAt: 88, unit: "200 GM", stock: 65, description: "Whole cumin seeds with warm earthy flavor." },
        { name: "Garam Masala", price: 90, compareAt: 115, unit: "100 GM", stock: 60, description: "Aromatic blend of premium Indian spices." },
        { name: "Chaat Masala", price: 75, compareAt: 95, unit: "100 GM", stock: 50, description: "Tangy spice mix for chaat and fruit salads." },
        { name: "Black Pepper Powder", price: 120, compareAt: 150, unit: "100 GM", stock: 55, description: "Freshly ground black pepper with pungent aroma." },
        { name: "Cardamom Green", price: 250, compareAt: 310, unit: "50 GM", stock: 40, description: "Premium green cardamom pods with intense flavor." },
        { name: "Cloves / Laung", price: 180, compareAt: 225, unit: "100 GM", stock: 45, description: "Whole cloves with strong aromatic essential oils." },
        { name: "Cinnamon Sticks", price: 100, compareAt: 128, unit: "100 GM", stock: 50, description: "Premium cinnamon sticks for sweet and savory dishes." },
        { name: "Bay Leaves / Tej Patta", price: 35, compareAt: 48, unit: "50 GM", stock: 65, description: "Aromatic bay leaves for flavoring curries and rice." },
        { name: "Nutmeg / Jaiphal", price: 60, compareAt: 78, unit: "50 GM", stock: 35, description: "Whole nutmeg with warm sweet-spicy flavor." },
        { name: "Star Anise / Chakra Phool", price: 120, compareAt: 150, unit: "50 GM", stock: 30, description: "Star-shaped spice with strong licorice flavor." },
        { name: "Sesame Seeds / Til", price: 65, compareAt: 82, unit: "200 GM", stock: 55, description: "White sesame seeds for garnishing and cooking." },
        { name: "Dry Mango Powder / Amchur", price: 70, compareAt: 88, unit: "200 GM", stock: 40, description: "Tangy dried mango powder for chat and curries." },
        { name: "Asafoetida / Hing", price: 50, compareAt: 65, unit: "50 GM", stock: 60, description: "Strong-smelling spice essential for dal tadka." },
        { name: "Saffron / Kesar", price: 500, compareAt: 620, unit: "2 GM", stock: 20, description: "Premium Kashmiri saffron with rich color and aroma." },
        { name: "Vanilla Extract", price: 180, compareAt: 225, unit: "30 ML", stock: 30, description: "Pure vanilla extract for baking and desserts." },
        { name: "Tandoori Masala", price: 85, compareAt: 108, unit: "200 GM", stock: 40, description: "Spicy tandoori masala for grilled dishes." },
        { name: "Pav Bhaji Masala", price: 80, compareAt: 100, unit: "200 GM", stock: 45, description: "Authentic spice blend for pav bhaji." },
      ],
    },
    {
      name: "Sauces, Spreads & Condiments",
      slug: "sauces-spreads-condiments",
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop",
      products: [
        { name: "Tomato Ketchup", price: 45, compareAt: 58, unit: "500 GM", stock: 100, description: "Thick and rich tomato ketchup from Maggi." },
        { name: "Schezwan Sauce", price: 60, compareAt: 78, unit: "200 GM", stock: 70, description: "Spicy schezwan sauce for Indo-Chinese dishes." },
        { name: "Soy Sauce", price: 55, compareAt: 70, unit: "200 ML", stock: 65, description: "Premium dark soy sauce for stir-fry and marinades." },
        { name: "Vinegar White", price: 40, compareAt: 52, unit: "200 ML", stock: 60, description: "Distilled white vinegar for pickling and cooking." },
        { name: "Vinegar Apple Cider", price: 80, compareAt: 100, unit: "200 ML", stock: 50, description: "Raw apple cider vinegar with mother culture." },
        { name: "Mayonnaise", price: 90, compareAt: 115, unit: "500 GM", stock: 55, description: "Creamy egg mayonnaise for salads and sandwiches." },
        { name: "Mustard Sauce", price: 65, compareAt: 82, unit: "200 GM", stock: 40, description: "Sharp yellow mustard sauce for hot dogs and dips." },
        { name: "Hot Sauce", price: 55, compareAt: 70, unit: "100 ML", stock: 60, description: "Fiery red chili hot sauce for extra heat." },
        { name: "BBQ Sauce", price: 75, compareAt: 95, unit: "200 GM", stock: 45, description: "Smoky barbecue sauce for grilled meats." },
        { name: "Pasta Sauce Arrabbiata", price: 95, compareAt: 120, unit: "350 GM", stock: 35, description: "Spicy tomato pasta sauce with herbs and chili." },
        { name: "Peanut Butter Crunchy", price: 160, compareAt: 200, unit: "350 GM", stock: 50, description: "Crunchy peanut butter with roasted peanut pieces." },
        { name: "Chocolate Spread", price: 140, compareAt: 175, unit: "350 GM", stock: 55, description: "Hazelnut chocolate spread for toast and pancakes." },
        { name: "Jam Mixed Fruit", price: 70, compareAt: 88, unit: "500 GM", stock: 70, description: "Mixed fruit jam with real fruit pieces." },
        { name: "Marmalade Orange", price: 80, compareAt: 100, unit: "500 GM", stock: 45, description: "Bitter-sweet orange marmalade for breakfast." },
        { name: "Honey Pure", price: 200, compareAt: 250, unit: "500 GM", stock: 50, description: "Pure raw honey sourced from Himalayan farms." },
      ],
    },
    {
      name: "Ready to Eat & Instant Foods",
      slug: "ready-to-eat-instant",
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop",
      products: [
        { name: "MTR Pav Bhaji Mix", price: 55, compareAt: 70, unit: "200 GM", stock: 80, description: "Instant pav bhaji mix for restaurant-style taste." },
        { name: "MTR Sambar Mix", price: 50, compareAt: 65, unit: "200 GM", stock: 75, description: "Ready-to-cook sambar mix with authentic flavor." },
        { name: "MTR Rasam Mix", price: 40, compareAt: 52, unit: "200 GM", stock: 80, description: "Instant rasam mix for tangy tomato rasam." },
        { name: "Maggi Soup Tomato", price: 20, compareAt: 28, unit: "1 Pack", stock: 150, description: "Instant tomato soup just add hot water." },
        { name: "Yippee Cup Noodles", price: 30, compareAt: 40, unit: "1 Cup", stock: 120, description: "Ready-to-eat cup noodles in masala flavor." },
        { name: "Knorr Soup Hot & Sour", price: 25, compareAt: 35, unit: "1 Pack", stock: 100, description: "Instant hot and sour soup mix." },
        { name: "Ready to Eat Rajma", price: 95, compareAt: 120, unit: "300 GM", stock: 50, description: "Rajma masala ready to heat and serve." },
        { name: "Ready to Eat Chole", price: 95, compareAt: 120, unit: "300 GM", stock: 50, description: "Aromatic chole ready in minutes." },
        { name: "Ready to Eat Dal Makhani", price: 100, compareAt: 128, unit: "300 GM", stock: 45, description: "Creamy dal makhani restaurant style." },
        { name: "Instant Idli Mix", price: 45, compareAt: 58, unit: "500 GM", stock: 70, description: "Just add water for soft idlis." },
        { name: "Instant Dosa Mix", price: 50, compareAt: 65, unit: "500 GM", stock: 65, description: "No fermentation dosa mix for crispy dosas." },
        { name: "Instant Upma Mix", price: 40, compareAt: 52, unit: "200 GM", stock: 80, description: "Quick upma mix with vegetables and spices." },
        { name: "Instant Pongal Mix", price: 55, compareAt: 70, unit: "200 GM", stock: 50, description: "Traditional Tamil pongal ready in minutes." },
        { name: "Khichdi Mix", price: 45, compareAt: 58, unit: "200 GM", stock: 60, description: "Instant moong dal khichdi comfort food." },
        { name: "Pasta Quick Cook", price: 35, compareAt: 48, unit: "1 Pack", stock: 90, description: "Quick-cook pasta with cheesy sauce sachet." },
        { name: "Oats Masala Ready", price: 40, compareAt: 52, unit: "1 Pack", stock: 100, description: "Instant masala oats with vegetables." },
        { name: "Biryani Kit Veg", price: 120, compareAt: 150, unit: "1 Kit", stock: 40, description: "Complete veg biryani kit with all spices." },
      ],
    },
    {
      name: "Frozen Foods",
      slug: "frozen-foods",
      image: "https://images.unsplash.com/photo-1619566626922-71c5935a3e8c?w=400&h=400&fit=crop",
      products: [
        { name: "Frozen Green Peas", price: 60, compareAt: 78, unit: "500 GM", stock: 80, description: "Flash frozen green peas retaining natural sweetness." },
        { name: "Frozen Sweet Corn", price: 55, compareAt: 70, unit: "500 GM", stock: 75, description: "Sweet yellow corn kernels frozen at peak freshness." },
        { name: "Frozen Mixed Vegetables", price: 70, compareAt: 88, unit: "500 GM", stock: 60, description: "Mixed veggie pack with peas, corn, beans and carrots." },
        { name: "Frozen French Fries", price: 90, compareAt: 115, unit: "500 GM", stock: 70, description: "Perfectly cut fries ready to deep fry." },
        { name: "Frozen Chicken Nuggets", price: 140, compareAt: 175, unit: "500 GM", stock: 50, description: "Crunchy breaded chicken nuggets, oven ready." },
        { name: "Frozen Fish Fingers", price: 160, compareAt: 200, unit: "500 GM", stock: 40, description: "Crispy fish fingers made from premium fish fillets." },
        { name: "Frozen Pizza Margherita", price: 150, compareAt: 185, unit: "1 Piece", stock: 35, description: "Cheese pizza with tomato sauce on thin crust." },
        { name: "Frozen Paratha Aloo", price: 80, compareAt: 100, unit: "5 Pieces", stock: 60, description: "Stuffed aloo parathas ready to pan-fry." },
        { name: "Frozen Paratha Gobi", price: 85, compareAt: 108, unit: "5 Pieces", stock: 50, description: "Cauliflower stuffed parathas for quick breakfast." },
        { name: "Ice Cream Vanilla", price: 110, compareAt: 140, unit: "500 ML", stock: 45, description: "Creamy vanilla ice cream made with real cream." },
        { name: "Ice Cream Chocolate", price: 120, compareAt: 150, unit: "500 ML", stock: 40, description: "Rich Belgian chocolate ice cream." },
        { name: "Ice Cream Mango", price: 115, compareAt: 145, unit: "500 ML", stock: 40, description: "Real mango ice cream with Alphonso pulp." },
        { name: "Ice Cream Strawberry", price: 110, compareAt: 140, unit: "500 ML", stock: 35, description: "Strawberry ice cream with real fruit pieces." },
        { name: "Frozen Momos Veg", price: 120, compareAt: 150, unit: "12 Pieces", stock: 45, description: "Steamed veg momos with spicy dipping sauce." },
        { name: "Frozen Spring Rolls", price: 100, compareAt: 128, unit: "10 Pieces", stock: 50, description: "Crispy spring rolls with vegetable filling." },
        { name: "Frozen Waffles", price: 75, compareAt: 95, unit: "4 Pieces", stock: 40, description: "Belgian waffles ready to toast for breakfast." },
        { name: "Kulfi Malai", price: 60, compareAt: 78, unit: "1 Piece", stock: 60, description: "Traditional Indian malai kulfi with cardamom." },
        { name: "Frozen Berry Mix", price: 180, compareAt: 225, unit: "500 GM", stock: 25, description: "Mixed berries frozen for smoothies and baking." },
      ],
    },
    {
      name: "Organic & Health Foods",
      slug: "organic-health-foods",
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop",
      products: [
        { name: "Organic Brown Rice", price: 120, compareAt: 150, unit: "1 KG", stock: 50, description: "Certified organic brown rice with intact bran." },
        { name: "Organic Quinoa", price: 280, compareAt: 350, unit: "500 GM", stock: 30, description: "Protein-rich quinoa, a complete superfood grain." },
        { name: "Organic Chia Seeds", price: 220, compareAt: 275, unit: "250 GM", stock: 40, description: "Omega-3 rich chia seeds for puddings and drinks." },
        { name: "Organic Coconut Sugar", price: 160, compareAt: 200, unit: "500 GM", stock: 35, description: "Natural low-glycemic sweetener from coconut sap." },
        { name: "Organic Lentils Mix", price: 110, compareAt: 140, unit: "500 GM", stock: 45, description: "Mixed organic lentils for protein-rich meals." },
        { name: "Organic Honey", price: 250, compareAt: 310, unit: "250 GM", stock: 35, description: "Certified organic raw honey from wild forests." },
        { name: "Organic Apple Cider", price: 120, compareAt: 150, unit: "500 ML", stock: 30, description: "Raw organic apple cider vinegar with mother." },
        { name: "Organic Peanut Butter", price: 200, compareAt: 250, unit: "350 GM", stock: 40, description: "100% organic peanuts ground into creamy butter." },
        { name: "Millets Mix", price: 85, compareAt: 108, unit: "500 GM", stock: 50, description: "Gluten-free millet grain mix for healthy eating." },
        { name: "Flax Seeds", price: 80, compareAt: 100, unit: "250 GM", stock: 60, description: "Ground flax seeds rich in omega-3 fatty acids." },
        { name: "Hemp Seeds", price: 180, compareAt: 225, unit: "200 GM", stock: 25, description: "Shelled hemp seeds with complete plant protein." },
        { name: "Protein Powder Whey", price: 550, compareAt: 680, unit: "500 GM", stock: 20, description: "Whey protein isolate for muscle recovery." },
        { name: "Vitamin C Effervescent", price: 120, compareAt: 150, unit: "1 Box", stock: 40, description: "Effervescent vitamin C tablets for immunity." },
        { name: "Protein Bar", price: 60, compareAt: 78, unit: "1 Bar", stock: 100, description: "Chocolate protein bar with 15g protein." },
        { name: "Organic Green Gram", price: 90, compareAt: 115, unit: "500 GM", stock: 50, description: "Organic whole moong rich in protein and fiber." },
      ],
    },
    {
      name: "Meat, Chicken & Seafood",
      slug: "meat-chicken-seafood",
      image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=400&fit=crop",
      products: [
        { name: "Chicken Breast Boneless", price: 220, compareAt: 270, unit: "500 GM", stock: 60, description: "Skinless boneless chicken breast lean and tender." },
        { name: "Chicken Thigh Boneless", price: 180, compareAt: 225, unit: "500 GM", stock: 55, description: "Boneless chicken thigh meat juicy and flavorful." },
        { name: "Chicken Drumstick", price: 160, compareAt: 200, unit: "500 GM", stock: 50, description: "Chicken drumsticks perfect for roasting and frying." },
        { name: "Chicken Whole", price: 350, compareAt: 430, unit: "1 Piece", stock: 30, description: "Whole dressed chicken for curries and roasting." },
        { name: "Mutton Curry Cut", price: 380, compareAt: 470, unit: "500 GM", stock: 40, description: "Graded mutton pieces with bone for rich curries." },
        { name: "Mutton Boneless", price: 460, compareAt: 560, unit: "500 GM", stock: 30, description: "Tender boneless mutton cubes for stir-fry." },
        { name: "Fish Rohu", price: 180, compareAt: 225, unit: "500 GM", stock: 35, description: "Freshwater Rohu fish steaks for curry." },
        { name: "Fish Pomfret", price: 280, compareAt: 350, unit: "500 GM", stock: 25, description: "Silver pomfret with delicate white flesh." },
        { name: "Fish Mackerel", price: 140, compareAt: 175, unit: "500 GM", stock: 40, description: "Indian mackerel rich in omega-3 fatty acids." },
        { name: "Prawns Large", price: 320, compareAt: 400, unit: "500 GM", stock: 30, description: "Large river prawns cleaned and deveined." },
        { name: "Prawns Small", price: 220, compareAt: 270, unit: "500 GM", stock: 35, description: "Small sized prawns perfect for curries." },
        { name: "Chicken Sausages", price: 120, compareAt: 150, unit: "250 GM", stock: 60, description: "Smoked chicken sausages ready to pan fry." },
        { name: "Chicken Seekh Kebab", price: 180, compareAt: 225, unit: "250 GM", stock: 40, description: "Spiced minced chicken seekh kebabs ready to grill." },
        { name: "Mutton Seekh Kebab", price: 240, compareAt: 300, unit: "250 GM", stock: 30, description: "Traditional minced mutton seekh kebabs." },
        { name: "Chicken Wings", price: 160, compareAt: 200, unit: "500 GM", stock: 45, description: "Chicken party wings for baking or deep frying." },
        { name: "Fish Basa Fillet", price: 200, compareAt: 250, unit: "500 GM", stock: 35, description: "Boneless basa fillets with mild white flesh." },
        { name: "Crab Meat", price: 280, compareAt: 350, unit: "250 GM", stock: 20, description: "Fresh crab meat for seafood delicacies." },
        { name: "Squid / Calamari", price: 200, compareAt: 250, unit: "500 GM", stock: 25, description: "Clean squid rings perfect for frying." },
      ],
    },
    {
      name: "Baby & Kids Foods",
      slug: "baby-kids-foods",
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop",
      products: [
        { name: "Cerelac Wheat", price: 160, compareAt: 200, unit: "300 GM", stock: 60, description: "Wheat-based infant cereal with milk and vitamins." },
        { name: "Cerelac Rice", price: 160, compareAt: 200, unit: "300 GM", stock: 55, description: "Rice-based baby cereal for early weaning." },
        { name: "Cerelac Multigrain", price: 180, compareAt: 225, unit: "300 GM", stock: 45, description: "Multigrain cereal with fruits for balanced nutrition." },
        { name: "Nestle Lactogen 1", price: 380, compareAt: 470, unit: "400 GM", stock: 40, description: "Infant formula for babies 0-6 months." },
        { name: "Nestle Lactogen 2", price: 360, compareAt: 450, unit: "400 GM", stock: 35, description: "Follow-up formula for babies 6-12 months." },
        { name: "Baby Wipes", price: 80, compareAt: 100, unit: "1 Pack", stock: 100, description: "Gentle baby wipes with aloe vera and vitamin E." },
        { name: "Baby Diapers Small", price: 240, compareAt: 300, unit: "1 Pack", stock: 50, description: "Soft and absorbent diapers for newborns." },
        { name: "Baby Diapers Medium", price: 280, compareAt: 350, unit: "1 Pack", stock: 45, description: "Medium size diapers for growing babies." },
        { name: "Baby Lotion", price: 120, compareAt: 150, unit: "200 ML", stock: 55, description: "Moisturizing baby lotion with gentle formula." },
        { name: "Baby Shampoo", price: 110, compareAt: 140, unit: "200 ML", stock: 50, description: "Tear-free baby shampoo with mild cleansers." },
        { name: "Baby Oil", price: 100, compareAt: 128, unit: "200 ML", stock: 60, description: "Pure baby oil for gentle massage and moisturizing." },
        { name: "Baby Powder", price: 90, compareAt: 115, unit: "200 GM", stock: 65, description: "Talc-free baby powder with cornstarch base." },
        { name: "Baby Food Pouch Apple", price: 55, compareAt: 70, unit: "1 Pouch", stock: 80, description: "Organic apple puree pouch for toddlers." },
        { name: "Teething Biscuits", price: 65, compareAt: 82, unit: "1 Pack", stock: 60, description: "Hard wheat biscuits for baby teething relief." },
        { name: "Baby Cereal Banana", price: 175, compareAt: 218, unit: "300 GM", stock: 40, description: "Banana flavored baby cereal with milk." },
      ],
    },
    {
      name: "Personal Care",
      slug: "personal-care",
      image: "https://images.unsplash.com/photo-1628088062854-b1870b1f6b9f?w=400&h=400&fit=crop",
      products: [
        { name: "Lifebuoy Soap", price: 35, compareAt: 48, unit: "1 Pack", stock: 120, description: "Antibacterial soap for complete germ protection." },
        { name: "Dettol Soap", price: 40, compareAt: 52, unit: "1 Pack", stock: 100, description: "Skin care soap with Dettol antiseptic protection." },
        { name: "Lux Soap", price: 38, compareAt: 50, unit: "1 Pack", stock: 110, description: "Luxurious beauty bar with soft fragrance." },
        { name: "Dove Soap", price: 45, compareAt: 58, unit: "1 Pack", stock: 100, description: "Moisturizing beauty bar with 1/4 moisturizing cream." },
        { name: "Head & Shoulders Shampoo", price: 120, compareAt: 150, unit: "200 ML", stock: 70, description: "Anti-dandruff shampoo with zinc formula." },
        { name: "Clinic Plus Shampoo", price: 60, compareAt: 78, unit: "200 ML", stock: 90, description: "Family shampoo with nourishing proteins." },
        { name: "Pantene Shampoo", price: 140, compareAt: 175, unit: "200 ML", stock: 65, description: "Hair fall control shampoo with pro-v formula." },
        { name: "Sunsilk Shampoo", price: 95, compareAt: 120, unit: "200 ML", stock: 70, description: "Sunsilk shampoo for silky smooth hair." },
        { name: "Colgate Toothpaste", price: 80, compareAt: 100, unit: "150 GM", stock: 100, description: "Cavity protection toothpaste with fluoride." },
        { name: "Pepsodent Toothpaste", price: 70, compareAt: 88, unit: "150 GM", stock: 95, description: "Whitening toothpaste for brighter teeth." },
        { name: "Sensodyne Toothpaste", price: 160, compareAt: 200, unit: "100 GM", stock: 50, description: "Sensitive teeth toothpaste with potassium nitrate." },
        { name: "Closeup Toothpaste", price: 75, compareAt: 95, unit: "150 GM", stock: 85, description: "Fresh breath toothpaste with mouthwash beads." },
        { name: "Dove Body Wash", price: 150, compareAt: 185, unit: "250 ML", stock: 60, description: "Gentle body wash with moisturizing cream." },
        { name: "Nivea Body Lotion", price: 180, compareAt: 225, unit: "200 ML", stock: 55, description: "Deep moisture body lotion for dry skin." },
        { name: "Vaseline Petroleum Jelly", price: 55, compareAt: 70, unit: "100 ML", stock: 80, description: "Pure petroleum jelly for dry skin protection." },
        { name: "Ponds Talcum Powder", price: 90, compareAt: 115, unit: "200 GM", stock: 70, description: "Fragrant talcum powder for all-day freshness." },
        { name: "Gillette Shaving Cream", price: 95, compareAt: 120, unit: "100 GM", stock: 60, description: "Rich foaming shaving cream for smooth shave." },
        { name: "Dove Deodorant", price: 180, compareAt: 225, unit: "150 ML", stock: 50, description: "Anti-perspirant deodorant with 48-hour protection." },
      ],
    },
    {
      name: "Household Essentials",
      slug: "household-essentials",
      image: "https://images.unsplash.com/photo-1566385101042-1a0aa68c5e47?w=400&h=400&fit=crop",
      products: [
        { name: "Surf Excel Detergent", price: 180, compareAt: 225, unit: "1 KG", stock: 80, description: "Front-load laundry detergent for deep stain removal." },
        { name: "Tide Detergent", price: 160, compareAt: 200, unit: "1 KG", stock: 90, description: "Laundry detergent that removes tough stains." },
        { name: "Ariel Detergent", price: 200, compareAt: 250, unit: "1 KG", stock: 70, description: "Premium laundry detergent with stain removal power." },
        { name: "Rin Soap Bar", price: 30, compareAt: 40, unit: "1 Bar", stock: 150, description: "Laundry soap bar for hand washing clothes." },
        { name: "Vim Liquid", price: 45, compareAt: 58, unit: "500 ML", stock: 100, description: "Lemon-scented dish wash liquid." },
        { name: "Lizol Floor Cleaner", price: 80, compareAt: 100, unit: "500 ML", stock: 65, description: "Disinfectant floor cleaner with fresh fragrance." },
        { name: "Harpic Toilet Cleaner", price: 90, compareAt: 115, unit: "500 ML", stock: 60, description: "Powerful toilet cleaner with thick gel formula." },
        { name: "Ujala Blue", price: 25, compareAt: 35, unit: "100 ML", stock: 120, description: "Optical whitener for white clothes." },
        { name: "Godrej Dishwash Bar", price: 20, compareAt: 28, unit: "1 Bar", stock: 160, description: "Economical dishwashing bar for daily use." },
        { name: "Cif Cream Cleaner", price: 65, compareAt: 82, unit: "500 ML", stock: 50, description: "Multi-purpose cream cleaner for kitchen surfaces." },
        { name: "Hit Insect Killer", price: 120, compareAt: 150, unit: "1 Can", stock: 45, description: "Aerosol spray for flying and crawling insects." },
        { name: "Good Knight Liquid", price: 70, compareAt: 88, unit: "1 Pack", stock: 80, description: "Mosquito repellent liquid with machine." },
        { name: "Odomos Mosquito Repellent", price: 55, compareAt: 70, unit: "100 GM", stock: 90, description: "Anti-mosquito cream for skin protection." },
        { name: "Mortein Spray", price: 140, compareAt: 175, unit: "1 Can", stock: 40, description: "Fast-acting insect killer spray." },
        { name: "Colin Glass Cleaner", price: 60, compareAt: 78, unit: "500 ML", stock: 55, description: "Streak-free glass and mirror cleaner." },
      ],
    },
    {
      name: "Pet Supplies",
      slug: "pet-supplies",
      image: "https://images.unsplash.com/photo-1619566626922-71c5935a3e8c?w=400&h=400&fit=crop",
      products: [
        { name: "Pedigree Dog Food Dry", price: 280, compareAt: 350, unit: "1 KG", stock: 40, description: "Complete dry dog food with chicken and vegetables." },
        { name: "Pedigree Wet Food", price: 60, compareAt: 78, unit: "1 Pouch", stock: 60, description: "Gravy-style wet dog food with real chicken." },
        { name: "Whiskas Cat Food Dry", price: 320, compareAt: 400, unit: "1 KG", stock: 35, description: "Dry cat food with fish and poultry flavors." },
        { name: "Whiskas Cat Wet Food", price: 55, compareAt: 70, unit: "1 Pouch", stock: 50, description: "Wet cat food in gravy with ocean fish." },
        { name: "Dog Biscuits Large", price: 120, compareAt: 150, unit: "500 GM", stock: 45, description: "Crunchy dog biscuits for dental health." },
        { name: "Dog Treats Chicken", price: 90, compareAt: 115, unit: "1 Pack", stock: 55, description: "Soft chicken flavored dog training treats." },
        { name: "Cat Treats Tuna", price: 80, compareAt: 100, unit: "1 Pack", stock: 40, description: "Tuna flavored crunchy cat treats." },
        { name: "Cat Litter", price: 250, compareAt: 310, unit: "1 KG", stock: 30, description: "Clumping cat litter with odor control." },
        { name: "Dog Shampoo", price: 160, compareAt: 200, unit: "200 ML", stock: 35, description: "Gentle dog shampoo with oatmeal formula." },
        { name: "Pet Chew Bone", price: 65, compareAt: 82, unit: "1 Piece", stock: 60, description: "Durable nylon chew bone for dogs." },
        { name: "Bird Seed Mix", price: 100, compareAt: 128, unit: "500 GM", stock: 40, description: "Mixed bird seeds for parrots and finches." },
        { name: "Fish Food Flakes", price: 60, compareAt: 78, unit: "100 GM", stock: 55, description: "Complete diet fish flakes for tropical fish." },
        { name: "Hamster Food Mix", price: 90, compareAt: 115, unit: "500 GM", stock: 25, description: "Nutritious seed mix for hamsters and gerbils." },
      ],
    },
    {
      name: "Beauty & Cosmetics",
      slug: "beauty-cosmetics",
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&h=400&fit=crop",
      products: [
        { name: "Maybelline Foundation", price: 320, compareAt: 400, unit: "1 Piece", stock: 40, description: "Liquid foundation with natural matte finish." },
        { name: "Lakme Face Powder", price: 180, compareAt: 225, unit: "1 Piece", stock: 55, description: "Compact face powder for oil-free glow." },
        { name: "Loreal Lipstick", price: 280, compareAt: 350, unit: "1 Piece", stock: 45, description: "Long-lasting lipstick with moisturizing formula." },
        { name: "Lakme Lipstick", price: 220, compareAt: 270, unit: "1 Piece", stock: 50, description: "Creamy lipstick with vibrant color payoff." },
        { name: "Maybelline Mascara", price: 300, compareAt: 380, unit: "1 Piece", stock: 35, description: "Volume-building mascara for dramatic lashes." },
        { name: "Lakme Kajal", price: 150, compareAt: 185, unit: "1 Piece", stock: 70, description: "Deep black kajal with creamy smudge-proof formula." },
        { name: "Maybelline Eyeliner", price: 250, compareAt: 310, unit: "1 Piece", stock: 40, description: "Precision liquid eyeliner for sharp wings." },
        { name: "Loreal Serum", price: 450, compareAt: 550, unit: "30 ML", stock: 25, description: "Hair serum for frizz-free silky shine." },
        { name: "Nivea Cream", price: 120, compareAt: 150, unit: "100 ML", stock: 80, description: "Moisturizing cream for soft healthy skin." },
        { name: "Ponds Cold Cream", price: 95, compareAt: 120, unit: "100 ML", stock: 70, description: "Deep moisturizing cold cream for dry skin." },
        { name: "Garnier Face Wash", price: 110, compareAt: 140, unit: "100 GM", stock: 80, description: "Brightening face wash with lemon extract." },
        { name: "Clean & Clear Face Wash", price: 90, compareAt: 115, unit: "100 ML", stock: 90, description: "Oil control face wash for acne-prone skin." },
        { name: "Fair and Lovely Cream", price: 75, compareAt: 95, unit: "50 GM", stock: 100, description: "Skin brightening cream with vitamin B3." },
        { name: "Lotus Face Pack", price: 140, compareAt: 175, unit: "100 GM", stock: 45, description: "Herbal face pack for glowing skin." },
        { name: "Biotique Face Wash", price: 130, compareAt: 165, unit: "100 ML", stock: 55, description: "Ayurvedic face wash with neem and tulsi." },
        { name: "Himalaya Face Wash", price: 80, compareAt: 100, unit: "100 ML", stock: 100, description: "Gentle face wash with neem and turmeric." },
        { name: "Nail Polish Red", price: 60, compareAt: 78, unit: "1 Piece", stock: 80, description: "Chip-resistant red nail polish with glossy shine." },
        { name: "Lip Balm", price: 35, compareAt: 48, unit: "1 Piece", stock: 120, description: "Moisturizing lip balm with SPF 15." },
      ],
    },
    {
      name: "Tea, Coffee & Health Drinks",
      slug: "tea-coffee-health-drinks",
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop",
      products: [
        { name: "Tata Tea Gold", price: 160, compareAt: 200, unit: "500 GM", stock: 80, description: "Premium CTC tea with rich golden color." },
        { name: "Taj Mahal Tea", price: 180, compareAt: 225, unit: "500 GM", stock: 70, description: "Luxurious tea blend with delicate flavor." },
        { name: "Red Label Tea", price: 150, compareAt: 185, unit: "500 GM", stock: 85, description: "Natural care tea with Ayurvedic herbs." },
        { name: "Tata Tea Green", price: 130, compareAt: 165, unit: "250 GM", stock: 50, description: "Pure green tea with antioxidant benefits." },
        { name: "Lipton Green Tea", price: 140, compareAt: 175, unit: "1 Box", stock: 55, description: "Honey lemon green tea bags for wellness." },
        { name: "Chakra Gold Tea", price: 120, compareAt: 150, unit: "500 GM", stock: 65, description: "Strong CTC tea for everyday chai." },
        { name: "Nescafe Classic", price: 180, compareAt: 225, unit: "200 GM", stock: 70, description: "Instant coffee granules with rich aroma." },
        { name: "Bru Instant Coffee", price: 160, compareAt: 200, unit: "200 GM", stock: 65, description: "South Indian filter coffee instant mix." },
        { name: "Bru Gold", price: 220, compareAt: 275, unit: "200 GM", stock: 45, description: "Premium freeze-dried coffee granules." },
        { name: "Coffee Beans Arabica", price: 350, compareAt: 430, unit: "250 GM", stock: 25, description: "Arabica coffee beans from Chikmagalur." },
        { name: "Bournvita", price: 200, compareAt: 250, unit: "500 GM", stock: 70, description: "Health drink powder with chocolate malt flavor." },
        { name: "Horlicks", price: 190, compareAt: 240, unit: "500 GM", stock: 75, description: "Classic health drink for growing kids." },
        { name: "Boost", price: 195, compareAt: 245, unit: "500 GM", stock: 70, description: "Energy health drink with glucose and vitamins." },
        { name: "Complan", price: 220, compareAt: 275, unit: "500 GM", stock: 55, description: "Nutritious health drink with protein and calcium." },
        { name: "Milo", price: 180, compareAt: 225, unit: "500 GM", stock: 60, description: "Malted chocolate drink mix with vitamins." },
        { name: "Bournvita Lite", price: 210, compareAt: 260, unit: "500 GM", stock: 40, description: "Low sugar health drink for adults." },
        { name: "Green Tea Lemon", price: 110, compareAt: 140, unit: "1 Box", stock: 50, description: "Lemon green tea bags fresh and zesty." },
        { name: "Ginger Tea Masala", price: 90, compareAt: 115, unit: "250 GM", stock: 60, description: "Spiced ginger tea mix for instant chai." },
      ],
    },
    {
      name: "Pickles & Chutneys",
      slug: "pickles-chutneys",
      image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=400&h=400&fit=crop",
      products: [
        { name: "Mango Pickle Classic", price: 60, compareAt: 78, unit: "500 GM", stock: 80, description: "Traditional tangy mango pickle with mustard oil." },
        { name: "Lemon Pickle", price: 65, compareAt: 82, unit: "500 GM", stock: 70, description: "Salty tangy lemon pickle with Indian spices." },
        { name: "Mixed Pickle", price: 70, compareAt: 88, unit: "500 GM", stock: 65, description: "Assorted vegetable pickle with mixed flavors." },
        { name: "Chili Pickle", price: 55, compareAt: 70, unit: "500 GM", stock: 60, description: "Fiery green chili pickle with mustard seeds." },
        { name: "Garlic Pickle", price: 80, compareAt: 100, unit: "500 GM", stock: 50, description: "Pungent garlic pickle in spiced oil." },
        { name: "Gongura Pickle", price: 75, compareAt: 95, unit: "500 GM", stock: 40, description: "Andhra-style sorrel leaf pickle with tangy taste." },
        { name: "Tomato Pickle", price: 60, compareAt: 78, unit: "500 GM", stock: 55, description: "Spicy tomato pickle with roasted cumin." },
        { name: "Coriander Chutney", price: 45, compareAt: 58, unit: "200 GM", stock: 70, description: "Fresh coriander chutney ready to serve." },
        { name: "Mint Chutney", price: 45, compareAt: 58, unit: "200 GM", stock: 65, description: "Refreshing mint chutney with green chili." },
        { name: "Tamarind Chutney", price: 50, compareAt: 65, unit: "200 GM", stock: 60, description: "Sweet and sour tamarind chutney for chaat." },
        { name: "Coconut Chutney", price: 40, compareAt: 52, unit: "200 GM", stock: 70, description: "Fresh coconut chutney with roasted spices." },
        { name: "Mango Chutney Sweet", price: 55, compareAt: 70, unit: "200 GM", stock: 55, description: "Sweet mango chutney with ginger and spices." },
        { name: "Garlic Chutney Dry", price: 50, compareAt: 65, unit: "200 GM", stock: 50, description: "Dry garlic chutney powder with red chili." },
        { name: "Onion Chutney", price: 40, compareAt: 52, unit: "200 GM", stock: 60, description: "Spicy onion chutney for dosa and idli." },
        { name: "Red Chili Chutney", price: 45, compareAt: 58, unit: "200 GM", stock: 55, description: "Andhra-style red chili chutney fiery hot." },
      ],
    },
    {
      name: "Dry Fruits, Nuts & Seeds",
      slug: "dry-fruits-nuts-seeds",
      image: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=400&fit=crop",
      products: [
        { name: "Almonds / Badam", price: 450, compareAt: 550, unit: "500 GM", stock: 60, description: "Premium California almonds rich in vitamin E." },
        { name: "Cashews / Kaju", price: 480, compareAt: 590, unit: "500 GM", stock: 55, description: "Creamy cashew nuts from premium grades." },
        { name: "Pistachios / Pista", price: 550, compareAt: 680, unit: "500 GM", stock: 40, description: "Open shell pistachios with natural sweetness." },
        { name: "Walnuts / Akhrot", price: 420, compareAt: 520, unit: "500 GM", stock: 45, description: "English walnuts rich in omega-3 fatty acids." },
        { name: "Raisins / Kishmish", price: 180, compareAt: 225, unit: "500 GM", stock: 70, description: "Golden seedless raisins naturally sweet." },
        { name: "Dates Medjool", price: 350, compareAt: 430, unit: "500 GM", stock: 40, description: "Premium Medjool dates soft and caramel sweet." },
        { name: "Figs / Anjeer", price: 380, compareAt: 470, unit: "500 GM", stock: 30, description: "Dried figs with natural sweetness and fiber." },
        { name: "Dried Apricots", price: 320, compareAt: 400, unit: "500 GM", stock: 35, description: "Sun-dried apricots with tangy sweet taste." },
        { name: "Dried Cranberries", price: 280, compareAt: 350, unit: "500 GM", stock: 35, description: "Sweetened dried cranberries for baking." },
        { name: "Pecans", price: 480, compareAt: 590, unit: "500 GM", stock: 25, description: "Buttery pecan halves rich in antioxidants." },
        { name: "Brazil Nuts", price: 420, compareAt: 520, unit: "500 GM", stock: 20, description: "Selenium-rich Brazil nuts from Amazon." },
        { name: "Macadamia Nuts", price: 580, compareAt: 720, unit: "500 GM", stock: 20, description: "Luxurious macadamia nuts with buttery texture." },
        { name: "Pine Nuts", price: 520, compareAt: 650, unit: "250 GM", stock: 20, description: "Creamy pine nuts for pesto and garnishing." },
        { name: "Pumpkin Seeds", price: 140, compareAt: 175, unit: "250 GM", stock: 50, description: "Roasted pumpkin seeds rich in magnesium." },
        { name: "Sunflower Seeds", price: 90, compareAt: 115, unit: "250 GM", stock: 60, description: "Nutritious sunflower seeds for healthy snacking." },
        { name: "Flax Seeds Brown", price: 80, compareAt: 100, unit: "250 GM", stock: 55, description: "Brown flax seeds with high omega-3 content." },
        { name: "Mixed Nuts Combo", price: 380, compareAt: 470, unit: "500 GM", stock: 35, description: "Assorted premium nuts roasted and salted." },
        { name: "Tahini Sesame Paste", price: 200, compareAt: 250, unit: "250 GM", stock: 30, description: "Pure sesame seed paste for dips and spreads." },
      ],
    },
    {
      name: "Sweets & Indian Mithai",
      slug: "sweets-indian-mithai",
      image: "https://images.unsplash.com/photo-1619566626922-71c5935a3e8c?w=400&h=400&fit=crop",
      products: [
        { name: "Kaju Katli", price: 280, compareAt: 350, unit: "250 GM", stock: 40, description: "Diamond-shaped cashew fudge with silver leaf." },
        { name: "Barfi Coconut", price: 180, compareAt: 225, unit: "250 GM", stock: 45, description: "Creamy coconut barfi with cardamom flavor." },
        { name: "Gulab Jamun", price: 120, compareAt: 150, unit: "1 Box", stock: 55, description: "Soft milk dumplings in rose syrup." },
        { name: "Rasgulla", price: 110, compareAt: 140, unit: "1 Box", stock: 50, description: "Spongy cottage cheese balls in sugar syrup." },
        { name: "Rasmalai", price: 160, compareAt: 200, unit: "1 Box", stock: 40, description: "Soft paneer discs in sweet saffron milk." },
        { name: "Jalebi", price: 80, compareAt: 100, unit: "250 GM", stock: 60, description: "Crispy orange spirals soaked in sugar syrup." },
        { name: "Motichoor Laddu", price: 160, compareAt: 200, unit: "250 GM", stock: 50, description: "Fine gram flour boondi laddus sweet perfection." },
        { name: "Sohan Papdi", price: 140, compareAt: 175, unit: "250 GM", stock: 35, description: "Flaky layered gram flour sweet with almonds." },
        { name: "Mysore Pak", price: 170, compareAt: 210, unit: "250 GM", stock: 35, description: "Rich ghee-based gram flour sweet from Mysore." },
        { name: "Sooji Halwa", price: 90, compareAt: 115, unit: "250 GM", stock: 40, description: "Creamy semolina halwa with nuts and raisins." },
        { name: "Dharwad Peda", price: 200, compareAt: 250, unit: "250 GM", stock: 30, description: "Caramelized milk fudge from Dharwad." },
        { name: "Cham Cham", price: 130, compareAt: 165, unit: "250 GM", stock: 35, description: "Cylindrical cottage cheese sweet with coconut." },
        { name: "Kalakand", price: 190, compareAt: 240, unit: "250 GM", stock: 30, description: "Dense milk cake sweet with grainy texture." },
        { name: "Malai Sandwich", price: 150, compareAt: 185, unit: "250 GM", stock: 25, description: "Layered milk cream sandwich with nuts." },
        { name: "Kaju Roll", price: 320, compareAt: 400, unit: "250 GM", stock: 25, description: "Cashew rolled sweet with saffron filling." },
        { name: "Ghewar", price: 200, compareAt: 250, unit: "1 Piece", stock: 20, description: "Rajasthani disc-shaped sweet with rabri." },
        { name: "Balushahi", price: 120, compareAt: 150, unit: "250 GM", stock: 35, description: "Flaky deep-fried sweet in sugar glaze." },
        { name: "Pista Roll", price: 300, compareAt: 380, unit: "250 GM", stock: 25, description: "Pistachio rolled sweet with creamy center." },
      ],
    },
  ];

  // Clear existing data
  console.log("Clearing existing data...");
  await prisma.payment.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cartItem.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.user.deleteMany();
  console.log("Cleared all existing data.");

  const passwordHash = await bcrypt.hash("password123", 12);

  const admin = await prisma.user.create({
    data: {
      name: "Admin",
      email: "admin@grocery.com",
      passwordHash,
      role: "ADMIN",
      phone: "9876543210",
    },
  });
  console.log(`Created admin user: ${admin.email}`);

  const demoUser = await prisma.user.create({
    data: {
      name: "Demo User",
      email: "user@demo.com",
      passwordHash,
      role: "USER",
      phone: "9876543211",
    },
  });
  console.log(`Created demo user: ${demoUser.email}`);

  // Create categories and products
  let productIndex = 0;
  for (const cat of categories) {
    const category = await prisma.category.create({
      data: {
        name: cat.name,
        slug: cat.slug,
        image: cat.image,
      },
    });

    for (const prod of cat.products) {
      const slug = prod.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");

      await prisma.product.create({
        data: {
          name: prod.name,
          slug: `${slug}-${Math.random().toString(36).substring(2, 6)}`,
          price: prod.price,
          compareAt: prod.compareAt,
          unit: prod.unit,
          stock: prod.stock,
          categoryId: category.id,
          isAvailable: true,
          isFeatured: Math.random() > 0.7,
          images: [getProductImage(productIndex)],
          description: prod.description,
        },
      });
      productIndex++;
    }

    console.log(`Created category "${cat.name}" with ${cat.products.length} products`);
  }

  const productCount = await prisma.product.count();
  const categoryCount = await prisma.category.count();
  console.log(`\nSeeding complete!`);
  console.log(`  Categories: ${categoryCount}`);
  console.log(`  Products: ${productCount}`);
  console.log(`  Users: 2 (admin + demo)`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
